//
// Created by Or on 2/11/2024.
//

#ifndef CPP_PLAYGROUND_2_COPYCONSTRUCTORDEMO_H
#define CPP_PLAYGROUND_2_COPYCONSTRUCTORDEMO_H


void testCCUpCastingDemo();


#endif //CPP_PLAYGROUND_2_COPYCONSTRUCTORDEMO_H
