//
// Created by Or on 2/11/2024.
//

#ifndef CPP_PLAYGROUND_2_PRIVATEINHERITANCE_H
#define CPP_PLAYGROUND_2_PRIVATEINHERITANCE_H


void testPrivateInheritance();


#endif //CPP_PLAYGROUND_2_PRIVATEINHERITANCE_H
