//
// Created by Or on 1/12/2024.
//

#ifndef CPP_PLAYGROUND_2_FILLVECTOR_TICPP_H
#define CPP_PLAYGROUND_2_FILLVECTOR_TICPP_H


void testFillVector_TICPP();


#endif //CPP_PLAYGROUND_2_FILLVECTOR_TICPP_H
