//
// Created by Or on 1/12/2024.
//

#ifndef CPP_PLAYGROUND_2_FILLSTRING_TICPP_H
#define CPP_PLAYGROUND_2_FILLSTRING_TICPP_H


void testFillString_TICPP();


#endif //CPP_PLAYGROUND_2_FILLSTRING_TICPP_H
