//
// Created by Or on 1/12/2024.
//

#ifndef CPP_PLAYGROUND_2_HELLOSTRINGSTICPP_H
#define CPP_PLAYGROUND_2_HELLOSTRINGSTICPP_H


void testHelloStringsTICPP();


#endif //CPP_PLAYGROUND_2_HELLOSTRINGSTICPP_H
