//
// Created by Or on 2/14/2024.
//

#ifndef CPP_PLAYGROUND_2_OVERLOADINGANDOVERRIDINGANDVIRTUALS_H
#define CPP_PLAYGROUND_2_OVERLOADINGANDOVERRIDINGANDVIRTUALS_H


void overloadingAndOverridingAndVirtualsDemo();


#endif //CPP_PLAYGROUND_2_OVERLOADINGANDOVERRIDINGANDVIRTUALS_H
