//
// Created by Or on 2/18/2024.
//

#ifndef CPP_PLAYGROUND_2_STATICHIERARCHYNAVIGATION_H
#define CPP_PLAYGROUND_2_STATICHIERARCHYNAVIGATION_H


void testStaticHierarchyNavigation();


#endif //CPP_PLAYGROUND_2_STATICHIERARCHYNAVIGATION_H
