//
// Created by Or on 2/16/2024.
//

#ifndef CPP_PLAYGROUND_2_VIRTUALDESTRUCTORS_H
#define CPP_PLAYGROUND_2_VIRTUALDESTRUCTORS_H


void virtualDestructorsDemo();


#endif //CPP_PLAYGROUND_2_VIRTUALDESTRUCTORS_H
