//
// Created by Or on 1/27/2024.
//

#ifndef CPP_PLAYGROUND_2_FUNCTIONTABLETICPP_H
#define CPP_PLAYGROUND_2_FUNCTIONTABLETICPP_H


void functionTableDemo();


#endif //CPP_PLAYGROUND_2_FUNCTIONTABLETICPP_H
