//
// Created by Or on 1/26/2024.
//

#ifndef CPP_PLAYGROUND_2_PASSBYVALUE_TICPP_H
#define CPP_PLAYGROUND_2_PASSBYVALUE_TICPP_H

void passByValueDemo();


#endif //CPP_PLAYGROUND_2_PASSBYVALUE_TICPP_H
