//
// Created by Or on 1/26/2024.
//

#ifndef CPP_PLAYGROUND_2_PASSBYADDRESSTICPP_H
#define CPP_PLAYGROUND_2_PASSBYADDRESSTICPP_H


void passByAddressDemo();


#endif //CPP_PLAYGROUND_2_PASSBYADDRESSTICPP_H
