//
// Created by Or on 1/26/2024.
//

#ifndef CPP_PLAYGROUND_2_PASSBYREFERENCETICPP_H
#define CPP_PLAYGROUND_2_PASSBYREFERENCETICPP_H


void passByReferenceDemo();


#endif //CPP_PLAYGROUND_2_PASSBYREFERENCETICPP_H
