//
// Created by Or on 1/27/2024.
//

#ifndef CPP_PLAYGROUND_2_POINTERARITHMETICTICPP_H
#define CPP_PLAYGROUND_2_POINTERARITHMETICTICPP_H


void pointerArithmeticDemo();


#endif //CPP_PLAYGROUND_2_POINTERARITHMETICTICPP_H
