//
// Created by Or on 1/27/2024.
//

#ifndef CPP_PLAYGROUND_2_POINTERTOFUNCTIONTICPP_H
#define CPP_PLAYGROUND_2_POINTERTOFUNCTIONTICPP_H


void PointerToFunctionDemo();


#endif //CPP_PLAYGROUND_2_POINTERTOFUNCTIONTICPP_H
