//
// Created by Or on 1/27/2024.
//

#ifndef CPP_PLAYGROUND_2_SIMPLESTRUCTTICPP_H
#define CPP_PLAYGROUND_2_SIMPLESTRUCTTICPP_H


void simpleStructDemo();


#endif //CPP_PLAYGROUND_2_SIMPLESTRUCTTICPP_H
