//
// Created by Or on 1/30/2024.
//

#ifndef CPP_PLAYGROUND_2_SIZEOFSTRUCTTICPP_H
#define CPP_PLAYGROUND_2_SIZEOFSTRUCTTICPP_H


void sizeOfStructDemo();


#endif //CPP_PLAYGROUND_2_SIZEOFSTRUCTTICPP_H
