//
// Created by Or Hasson on 07/02/2024.
//

#ifndef CPP_PLAYGROUND_2_FREESTANDINGREFERENCES_H
#define CPP_PLAYGROUND_2_FREESTANDINGREFERENCES_H


void FreeStandingReferencesDemo();


#endif //CPP_PLAYGROUND_2_FREESTANDINGREFERENCES_H
